# Core resources: Namespace, Deployment, and Service
apiVersion: v1
kind: Namespace
metadata:
  name: sales-system

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales
  namespace: sales-system

spec:
  selector:
    matchLabels:
      app: sales

  template:
    metadata:
      labels:
        app: sales
    spec:
      terminationGracePeriodSeconds: 60

      containers:
        - name: sales
          image: sales-image

          ports:
            - name: sales
              containerPort: 3000
            - name: sales-debug
              containerPort: 3030

          readinessProbe: # readiness probes mark the service available to accept traffic.
            httpGet:
              path: /readiness
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 1

          livenessProbe: # liveness probes mark the service alive or dead (to be restarted).
            httpGet:
              path: /liveness
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 2

          env:
            - name: GOMAXPROCS # Dynamically sets the number of CPU cores based on the container's CPU limit
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu

---

apiVersion: v1
kind: Service
metadata:
  name: sales-service
  namespace: sales-system

spec:
  selector:
    app: sales

